#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    # Initialize all counters for positive, negative and zero elements
    pos_cnt = 0
    neg_cnt = 0
    zero_cnt = 0
    
    # Check for no of elements in array
    arr_len = calc_len(arr)
    
    # for loop to count all positive, negative and zero elements
    for i in arr:
        if i > 0:
            pos_cnt += 1
        elif i < 0:
            neg_cnt += 1
        else:
            zero_cnt += 1
    
    # Print results rounding answers to 6 decimal places
    print(round(pos_cnt / arr_len, 6))
    print(round(neg_cnt / arr_len, 6))
    print(round(zero_cnt / arr_len, 6))

# Function to check for no of elements in array    
def calc_len(arr):
    arr_cnt = 0
    for i in arr:
        arr_cnt += 1
    return(arr_cnt)

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
